export const secureStoreKeys = {
  CRYPTO_CLASH_USERNAME: 'CRYPTO_CLASH_USERNAME',
  CRYPTO_CLASH_PASSWORD_HASH: 'CRYPTO_CLASH_PASSWORD_HASH',
  CRYPTO_CLASH_WALLET_PRIVATE_KEY: 'CRYPTO_CLASH_WALLET_PRIVATE_KEY',
  CRYPTO_CLASH_WALLET_MNEMONIC: 'CRYPTO_CLASH_WALLET_MNEMONIC',
};
